export const FETCH_BET_HISTORY_SUC = 'FETCH_BET_HISTORY_SUC'
export const FETCH_BET_HISTORY_ERR = 'FETCH_BET_HISTORY_ERR'
export const INIT_BET_HISTORY = 'INIT_BET_HISTORY'

export const FETCH_BET_HISTORY_MORE_SUC = 'FETCH_BET_HISTORY_MORE_SUC'
export const FETCH_BET_HISTORY_MORE_ERR = 'FETCH_BET_HISTORY_MORE_ERR'

export const POST_SHARE_SUC = 'POST_SHARE_SUC'
export const POST_SHARE_ERR = 'POST_SHARE_ERR'

export const UPDATE_REWARD_TIME = 'UPDATE_REWARD_TIME'

export const FETCH_BET_DETAIL_SUC = 'FETCH_BET_DETAIL_SUC'
export const FETCH_BET_DETAIL_ERR = 'FETCH_BET_DETAIL_ERR'
export const INIT_BET_DETAIL = 'INIT_BET_DETAIL'

export const UPDATE_BET_SELECTED = 'UPDATE_BET_SELECTED'
export const UPDATE_SHOW_BET_SUC = 'UPDATE_SHOW_BET_SUC'
export const UPDATE_SHOW_BET_CONFIRM = 'UPDATE_SHOW_BET_CONFIRM'
export const UPDATE_BET_SHARE_IMG_INFO = 'UPDATE_BET_SHARE_IMG_INFO'
