export const FETCH_CHAMPION_LIST_SUC = 'FETCH_CHAMPION_LIST_SUC'
export const FETCH_CHAMPION_LIST_ERR = 'FETCH_CHAMPION_LIST_ERR'

export const FETCH_FINAL_LIST_SUC = 'FETCH_FINAL_LIST_SUC'
export const FETCH_FINAL_LIST_ERR = 'FETCH_FINAL_LIST_ERR'

export const UPDATE_CHAMPION_LIST = 'UPDATE_CHAMPION_LIST'
export const RESET_CHAMPION_LIST = 'RESET_CHAMPION_LIST'
export const INIT_CHAMPION_LIST = 'INIT_CHAMPION_LIST'

export const UPDATE_FINAL_LIST = 'UPDATE_FINAL_LIST'
export const RESET_FINAL_LIST = 'RESET_FINAL_LIST'
export const INIT_FINAL_LIST = 'INIT_FINAL_LIST'
export const FILTER_FINAL_LIST = 'FILTER_FINAL_LIST'
