export const FETCH_RULES_SUC = 'FETCH_RULES_SUC'
export const FETCH_RULES_ERR = 'FETCH_RULES_ERR'
export const FETCH_INVITE_INCOME_SUC = 'FETCH_INVITE_INCOME_SUC'
export const FETCH_INVITE_INCOME_ERR = 'FETCH_INVITE_INCOME_ERR'

export const POST_INVITE_SUC = 'POST_INVITE_SUC'
export const POST_INVITE_ERR = 'POST_INVITE_ERR'

export const FETCH_INVITE_SUC = 'FETCH_INVITE_SUC'
export const FETCH_INVITE_ERR = 'FETCH_INVITE_ERR'

export const INIT_INVITE_LIST = 'INIT_INVITE_LIST'

export const FETCH_INVITE_QR_SUC = 'FETCH_INVITE_QR_SUC'
export const FETCH_INVITE_QR_ERR = 'FETCH_INVITE_QR_ERR'
