export const FETCH_MALL_SUC = 'FETCH_MALL_SUC'
export const FETCH_MALL_ERR = 'FETCH_MALL_ERR'
export const INIT_MALL_LIST = 'INIT_MALL_LIST'

export const FETCH_MALL_MORE_SUC = 'FETCH_MALL_MORE_SUC'
export const FETCH_MALL_MORE_ERR = 'FETCH_MALL_MORE_ERR'

export const FETCH_GOODS_DETAIL_SUC = 'FETCH_GOODS_DETAIL_SUC'
export const FETCH_GOODS_DETAIL_ERR = 'FETCH_GOODS_DETAIL_ERR'
export const INIT_GOODS_DETAIL = 'INIT_GOODS_DETAIL'

export const FETCH_MALL_NOTICE_SUC = 'FETCH_MALL_NOTICE_SUC'
export const FETCH_MALL_NOTICE_ERR = 'FETCH_MALL_NOTICE_ERR'