export const INIT_MATCHES = 'INIT_MATCHES'
export const FETCH_MATCHES_SUC = 'FETCH_MATCHES_SUC'
export const FETCH_MATCHES_ERR = 'FETCH_MATCHES_ERR'
export const INIT_HOT_MATCHES = 'INIT_HOT_MATCHES'
export const FETCH_HOT_MATCHES_SUC = 'FETCH_HOT_MATCHES_SUC'
export const FETCH_HOT_MATCHES_ERR = 'FETCH_HOT_MATCHES_ERR'

export const BET_SUC = 'BET_SUC'
export const BET_ERR = 'BET_ERR'

export const UPDATE_MATCHES_DATA = 'UPDATE_MATCHES_DATA'
export const RESET_MATCHES_DATA = 'RESET_MATCHES_DATA'

export const FETCH_MATCH_DETAIL_SUC = 'FETCH_MATCH_DETAIL_SUC'
export const FETCH_MATCH_DETAIL_ERR = 'FETCH_MATCH_DETAIL_ERR'
export const RESET_MATCH_DETAIL = 'RESET_MATCH_DETAIL'

export const FETCH_CHAT_LIST_SUC = 'FETCH_CHAT_LIST_SUC'
export const FETCH_CHAT_LIST_ERR = 'FETCH_CHAT_LIST_ERR'
export const RESET_CHAT_LIST = 'RESET_CHAT_LIST'

export const FETCH_CHAT_LIST_MORE_SUC = 'FETCH_CHAT_LIST_MORE_SUC'
export const FETCH_CHAT_LIST_MORE_ERR = 'FETCH_CHAT_LIST_MORE_ERR'

export const SEND_MSG_SUC = 'SEND_MSG_SUC'

export const FILTER_MATCHES = 'FILTER_MATCHES'

export const FETCH_HISTORY_MATCHES_SUC = 'FETCH_HISTORY_MATCHES_SUC'
export const FETCH_HISTORY_MATCHES_ERR = 'FETCH_HISTORY_MATCHES_ERR'
export const INIT_HISTORY_MATCHES = 'INIT_HISTORY_MATCHES'
