export const FETCH_ORDER_LIST_SUC = 'FETCH_ORDER_LIST_SUC'
export const FETCH_ORDER_LIST_ERR = 'FETCH_ORDER_LIST_ERR'
export const INIT_ORDER_LIST = 'INIT_ORDER_LIST'
export const FETCH_ORDER_LIST_MORE_SUC = 'FETCH_ORDER_LIST_MORE_SUC'
export const FETCH_ORDER_LIST_MORE_ERR = 'FETCH_ORDER_LIST_MORE_ERR'

export const FETCH_ORDER_DETAIL_SUC = 'FETCH_ORDER_DETAIL_SUC'
export const FETCH_ORDER_DETAIL_ERR = 'FETCH_ORDER_DETAIL_ERR'
export const INIT_ORDER_DETAIL = 'INIT_ORDER_DETAIL'
