export const FETCH_DAILY_QUESTS_SUC = 'FETCH_DAILY_QUESTS_SUC'
export const FETCH_DAILY_QUESTS_ERR = 'FETCH_DAILY_QUESTS_ERR'

export const GET_DAILY_REWARD_SUC = 'GET_DAILY_REWARD_SUC'
export const GET_DAILY_REWARD_ERR = 'GET_DAILY_REWARD_ERR'

export const OPEN_SIGNIN = 'OPEN_SIGNIN'
export const CLOSE_SIGNIN = 'CLOSE_SIGNIN'

export const FETCH_QUESTS_SUC = 'FETCH_QUESTS_SUC'
export const FETCH_QUESTS_ERR = 'FETCH_QUESTS_ERR'
export const FETCH_EXTRA_QUESTS_SUC = 'FETCH_EXTRA_QUESTS_SUC'
export const FETCH_EXTRA_QUESTS_ERR = 'FETCH_EXTRA_QUESTS_ERR'

export const GET_REWARD_SUC = 'GET_REWARD_SUC'
export const GET_REWARD_ERR = 'GET_REWARD_ERR'
