export const FETCH_USER_INFO_SUC = 'FETCH_USER_INFO_SUC'
export const FETCH_USER_INFO_ERR = 'FETCH_USER_INFO_ERR'
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO'

export const FETCH_RED_POINT_SUC = 'FETCH_RED_POINT_SUC'
export const CLEAR_RED_POINT = 'CLEAR_RED_POINT'

export const UPDATE_SHOW_LOGIN = 'UPDATE_SHOW_LOGIN'
export const UPDATE_SHOW_ACTIVITY = 'UPDATE_SHOW_ACTIVITY'

export const SAVE_SHARE_USER_ID = 'SAVE_SHARE_USER_ID'
export const CLEAR_SHARE_USER_ID = 'CLEAR_SHARE_USER_ID'

export const SAVE_QRMARK = 'SAVE_QRMARK'
export const SAVE_CITY_MATCH_TOKEN = 'SAVE_CITY_MATCH_TOKEN'

export const UPDATE_SHOW_REWARD = 'UPDATE_SHOW_REWARD'
export const UPDATE_SHOW_WECHAT_GROUP = 'UPDATE_SHOW_WECHAT_GROUP'
export const UPDATE_SHOW_OFFICIAL_GUIDE = 'UPDATE_SHOW_OFFICIAL_GUIDE'
export const UPDATE_SHOW_HOME_DIALOG = 'UPDATE_SHOW_HOME_DIALOG'

export const MARK_CITY_MATCH_USER_SUC = 'MARK_CITY_MATCH_USER_SUC'
export const MARK_CITY_MATCH_USER_ERR = 'MARK_CITY_MATCH_USER_ERR'

export const FETCH_CITY_MATCH_INFO_SUC = 'FETCH_CITY_MATCH_INFO_SUC'
export const FETCH_CITY_MATCH_INFO_ERR = 'FETCH_CITY_MATCH_INFO_ERR'
export const UPDATE_CITY_MATCH_INFO = 'UPDATE_CITY_MATCH_INFO'
